name: MSBuild

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        msbuild /p:Configuration=Release /p:Platform=x64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BattleyeHostsManager-exe
        path: x64/Release/*.exe
